name: deify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.6
  firebase_core: 1.4.0
  google_sign_in: ^5.0.7
  firebase_auth: 3.0.1
  lottie: ^1.1.0
  font_awesome_flutter: ^9.1.0
  introduction_screen: ^2.1.0
  flutter_svg: ^0.22.0
  avatar_glow: 2.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
    - assets/models/
  uses-material-design: true

